# Generated by Django 3.0.1 on 2022-12-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        ('schedule', '0012_auto_20191025_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Calendar')),
                ('price', models.PositiveSmallIntegerField(help_text='(required) price per night per person')),
                ('single_bed_number', models.PositiveSmallIntegerField(help_text='(required) number of single beds in the room')),
                ('double_bed_number', models.PositiveSmallIntegerField(help_text='(required) number of double beds in the room')),
                ('bath_number', models.PositiveSmallIntegerField(help_text='(required) number of bathrooms in the room')),
                ('surface_area_sqmeter', models.PositiveSmallIntegerField(help_text='(required) surface of the room in square meters')),
                ('description', models.CharField(blank=True, help_text='(optional) room description', max_length=120, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_room', to='locations.Location')),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='(optional) room image field', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='(automatic) created date')),
                ('alt', models.CharField(default='blank', help_text='(required) SEO for images in order to provide accessibility for the visually impaired', max_length=120)),
                ('location', models.ForeignKey(help_text='(automatic) room model linkage', on_delete=django.db.models.deletion.PROTECT, related_name='room_image', to='rooms.Room')),
            ],
        ),
    ]
