# Generated by Django 3.0.1 on 2020-01-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Calendar')),
                ('price', models.PositiveSmallIntegerField()),
                ('single_bed_number', models.PositiveSmallIntegerField()),
                ('double_bed_number', models.PositiveSmallIntegerField()),
                ('bath_number', models.PositiveSmallIntegerField()),
                ('surface_area_sqmeter', models.PositiveSmallIntegerField()),
            ],
            bases=('schedule.calendar',),
        ),
    ]
