# Generated by Django 3.0.1 on 2022-12-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import klingon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='(required) title of the house/property card', max_length=120)),
                ('gps_location', models.CharField(blank=True, help_text='(required) gps location of the house/property', max_length=120, null=True)),
                ('gps_coordinates', models.CharField(blank=True, help_text='(required) gps coordinates of the house/property', max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='(automatic) timestamp for last update')),
                ('timestamp', models.DateTimeField(help_text='(automatic) timestamp for creation date')),
                ('slug', models.SlugField(help_text='(automatic) unique identifier for url location', unique=True)),
                ('tag', models.CharField(default='property', help_text='(automatic) unique tag', max_length=120)),
                ('content', models.TextField(blank=True, help_text='(optional) description of the house/property', null=True)),
                ('draft', models.BooleanField(default=False, help_text='(optional) description of the house/property')),
                ('user', models.ForeignKey(default=1, help_text='(automatic) model linkage with the User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
            bases=(models.Model, klingon.models.Translatable),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alt', models.CharField(default='blank', max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='locations.Location')),
            ],
        ),
    ]
