# Generated by Django 3.0.1 on 2020-01-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
