# Generated by Django 3.0.1 on 2019-12-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='alt',
            field=models.CharField(default='blank', max_length=120),
        ),
    ]
