# Generated by Django 3.0.1 on 2020-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200101_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
