# Generated by Django 3.0.1 on 2020-01-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_gps_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='gps_location',
        ),
    ]
