# Generated by Django 3.0.1 on 2019-12-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='property', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='property', max_length=120),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='alt',
            field=models.CharField(blank=True, default='blank', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='posts.Post'),
        ),
    ]
